### ISSUE TITLE
Pharo 64bits support

### ISSUE THREAD

**Issue by ThierryGoubier** [pharo-contributions/OSSubprocess#22] opened 2016-10-29 16:48 UTC
OSSubprocess fails to run on Pharo6 64 bits.

> Error: Error: posix_spawn(), code: 14, description: Mauvaise adresse
> OSSUnixSystemAccessor(Object)>>error:
> OSSUnixSystemAccessor>>strerror:message:
> OSSUnixSubprocess>>internalRun
> [ self internalRun ] in OSSUnixSubprocess>>run in Block: [ self internalRun ]
> BlockClosure>>ensure:
> OSSUnixSubprocess>>run
> OSSUnixSubprocess>>runAndWaitPollingEvery:retrievingStreams:onExitDo:

**Comment by StormBytePP** [comment] 2017-06-22 16:32
I am getting this error when trying to import a gitfiletree package.

**Comment by marianopeck** [comment] 2017-06-23 13:27
Yes, OSSubprocess doesn't work on Pharo 64 bits until I can make it work. And to make it work, I need a PR merged in the VM: https://github.com/pharo-project/pharo-vm/pull/108

**Comment by StormBytePP** [comment] 2017-08-22 11:34
References PR seems to be merged. Any news regarding this front?
It is becomming important, as there are many cases which maintain code via monticello packages, is not the best way.
Thanks

**Comment by marianopeck** [comment] 2017-08-22 11:51
The PR *was* merged but I think it was lost again, as I couldn't find the new primitives.

**Comment by StormBytePP** [comment] 2017-11-23 10:23
I have tested this on pharo6.1 64bit, and I am getting this primitive failed:

integerAt: byteOffset put: value size: nBytes signed: aBoolean
	"Primitive. Store the given value as integer of nBytes size
	in the receiver. Fail if the value is out of range.
	Note: This primitive will access memory in the outer space if
	invoked from ExternalAddress."
	<primitive: 'primitiveFFIIntegerAtPut' module:'SqueakFFIPrims'>
	^self primitiveFailed

**Comment by marianopeck** [comment] 2017-11-23 11:39
Hi @StormBytePP 

Yes, it is expected to fail as I assume 32 bites (4 bytes) pointers in a couple of places... 
And I think one of the places would be easier if this PR is integrated (which would happen soon): https://github.com/pharo-project/pharo-vm/pull/142

**Comment by akgrant43** [comment] 2018-02-21 18:16
Hi Mariano,

Can you expand on what you need from #142?

If it is only the pointer size, you can get this now with:

`FFIExternalType sizeOf: 'void *'`

Thanks,
Alistair

**Comment by marianopeck** [comment] 2018-02-26 10:59
Hi,

Sorry for the late answer. Actually, solving the 64 bits issue is much simpler, as Guille showed it in #30.  My point on #142 is that I wanted to take that opportunity to also get rid of lot of OSProcess code I am relying on now because I don't have #142.

**Comment by marianopeck** [comment] 2018-02-26 11:01
The work I wanted to do once #142 is integrated is in an old commit on the dev branch: https://github.com/marianopeck/OSSubprocess/commit/5d88003c093a2692a40e4612b6f57611b1d9f02e

**Comment by akgrant43** [comment] 2018-03-03 12:38
@marianopeck  The VMs on bintray at:

https://bintray.com/opensmalltalk/vm/cog/201803031106#files

include the two additional primitives in FilePlugin to open a file by descriptor and FILE*.

The extensions to FilePlugin are at:

https://github.com/akgrant43/AKG-FileSystem

I haven't written a BaselineOf yet, so you'll need to clone it in Iceberg and load the single package.

I'll convert the smalltalk code to a PR after the VM makes it to vmLatest.

The issue is being tracked at: 

https://pharo.fogbugz.com/f/cases/21462/Open-a-FileStream-based-on-fd-or-FILE
https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/222

**Comment by guillep** [comment] 2018-05-18 14:33
So, 64 bit support is already there, I'll close this issue, please open a new one for the other topics. Tx!

**Closed by guillep** 2018-05-18 14:33 UTC
